language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    update: true

before_install:
  - sudo bash before_install.sh

script:
  - make
  - bash tests/run.sh

before_deploy:
  - git config --local user.name "scopeinfinity"
  - git config --local user.email "gagan1kumar.cs@gmail.com"
  - git tag -f "latest"

deploy:
  provider: releases
  api_key:
    secure: "LAXKpTPXlyv9pfhEDzmon80mZf9/4Sm8aNrNmNiVW+znxL+hAJJETXTtwkvNrBON1jjFIfBHi/Walp1y0mAMmlFGHFvBvqfRakQn8yLSkZCgkBj/pmd4tDSZQFtOFmfBUrUR/5x+NVE0592c9K4fwkS8L0eOAO3bLdt2GGVdlUt5qDhiyHwTMm6wlklpWC/+w1ZuG89NJywx33VpAUJManuRyKHLEis252Kil20XaQp2aVWoIuhizcn+KdFqdqgjxR9vS8KeJVEBOu8mmDCERuoobISvpuG6OF4x0FFt7mHDBSxJgULqXKaj8+izcXA14ut2H3VXKXpTcIDFpAZ8U7J7bLkwsJq/OcjoJZUTHqE6NwGn5/CX0HQUiMO8AbuOtSNbgTwI//TYhkYX19zi02wG4nXugg9QqH1lKOD4MH13wajRMjvdI09n+RwIAx4d8irUILyiQUffbW6qvLDUqr3QawfhvXUO9EZVm2ytnCumA9Zs7xdB8zbl6Kp253Nfm5tQY7tvVyZx3Q/CiNNxbkS/U4/g/SZYi94dGNejZHs+Zee1y20eGm6HVFhpqwMB62xPr7xfG7xIo/9AsXfzf0yFzdOxD0qKBjrF4HTVgzijbjVJolWoJ0NX52Pcqz/t4TK3Bl6Zx80TrPr5cRMR24rxPcFmFckNWRhKoEzr72E="
  file: "build/image.vmdk"
  overwrite: true
  skip_cleanup: true
  on:
    tags: false
    branch: master