name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prerequisite
      run: sudo bash before_install.sh

    - name: make
      run: make

    - uses: actions/upload-artifact@v2
      with:
        name: OS Image
        path: build/image.vmdk
