name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prerequisite
      run: sudo bash before_install.sh

    - name: make test
      run: make test
