name: Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Prerequisite
      run: sudo bash before_install.sh

    - name: make test
      run: make test

    - uses: actions/upload-artifact@v2
      with:
        name: Test Sceenshots
        path: /tmp/*_test.ppm
